CREATE TABLE public.howwhatwhy(id SERIAL PRIMARY KEY, timestamp TIMESTAMP DEFAULT LOCALTIMESTAMP, hows INTEGER[], whats INTEGER[], whys INTEGER[]);

CREATE TABLE public.links( id INT PRIMARY KEY NOT NULL, href VARCHAR(255) NOT NULL, text VARCHAR(255) NOT NULL);

CREATE UNIQUE INDEX links_id_uindex ON public.links (id);